### ISSUE TITLE
Using datetime cast on Encrypted fails

### ISSUE THREAD

**Issue by rawilk** [Crudly/Encrypted#1]
I'm using Laravel 7.9, and using the Encrypted cast using a datetime cast, it fails:

```php
class Student extends Model
{
    protected $casts = [
        'birth_date' => Encrypted::class . ':datetime',
    ];
}

$student->birth_date; // fails
```

> Call to undefined method "getConnection".

It looks like `HasAttributes` is calling the `getConnection()` method, which is in `Model` to get the date format if a date format is not set.

I think the simplest solution would be setting the `$dateFormat` field in `Caster`, although it's really only needed for date fields.

**Comment by tontonsb** [comment]
Thank you for the report and expecially for looking into it further and telling me where the issue is!

I did add a bit more - we will forward the `getDateFormat` call to the model. I think that will be more predicatable behaviour.

Will make a release as soon as the Travis tests are done and green.
